config/routes.rb
Rails.application.routes.draw do

  resources :personals

  resources :alunos

  devise_for :users
  root :to => "alunos#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/aluno.rb
# == Schema Information
#
# Table name: alunos
#
#  id         :integer          not null, primary key
#  first_name :string           not null
#  last_name  :string           not null
#  birthdate  :date             not null
#  email      :string           not null
#  mobile     :string           not null
#  gender     :string           not null
#  avatar     :string
#  status     :integer          not null
#  more_info  :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Aluno < ActiveRecord::Base
  belongs_to :user
  enum status: { pending:0, active:1, inactive:2 }
  validates_presence_of :first_name, :last_name, :birthdate, :email, :mobile, :gender, :status, :user

  def fullname
    "#{first_name} #{last_name}"
  end

  def age
    now = Time.now.utc.to_date
    now.year - birthdate.year - ((now.month > birthdate.month || (now.month == birthdate.month && now.day >= birthdate.day)) ? 0 : 1)
  end

  def humanize_gender
    return "Feminino" if gender == "F"
    return "Masculino" if gender == "M"
    return "Outro" if gender == "O"
  end
end

app/models/personal.rb
# == Schema Information
#
# Table name: personals
#
#  id         :integer          not null, primary key
#  first_name :string           not null
#  last_name  :string           not null
#  birthdate  :date             not null
#  email      :string           not null
#  mobile     :string           not null
#  cref       :string           not null
#  gender     :string           not null
#  avatar     :string
#  status     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Personal < ActiveRecord::Base
  belongs_to :user
  enum status: { pending:0, active:1, inactive:2 }
  validates_presence_of :first_name, :last_name, :birthdate, :email, :mobile, :cref, :gender, :status, :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :aluno
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @alunos = Aluno.all
    respond_with(@alunos)
  end

  def show
    respond_with(@aluno)
  end

  def new
    @aluno = Aluno.new
    respond_with(@aluno)
  end

  def edit
  end

  def create
    @aluno = Aluno.new(aluno_params)
    @aluno.save
    respond_with(@aluno)
  end

  def update
    @aluno.update(aluno_params)
    respond_with(@aluno)
  end

  def destroy
    @aluno.destroy
    respond_with(@aluno)
  end

  private
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    def aluno_params
      params.require(:aluno).permit(:first_name, :lastname, :birthdate, :email, :mobile, :gender, :avatar, :status, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @personals = Personal.all
    respond_with(@personals)
  end

  def show
    respond_with(@personal)
  end

  def new
    @personal = Personal.new
    respond_with(@personal)
  end

  def edit
  end

  def create
    @personal = Personal.new(personal_params)
    @personal.save
    respond_with(@personal)
  end

  def update
    @personal.update(personal_params)
    respond_with(@personal)
  end

  def destroy
    @personal.destroy
    respond_with(@personal)
  end

  private
    def set_personal
      @personal = Personal.find(params[:id])
    end

    def personal_params
      params.require(:personal).permit(:first_name, :last_name, :birthdate, :email, :mobile, :cref, :gender, :avatar, :status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper

  DATE='%d/%m/%Y'
  DATE_TIME='%d/%m/%Y %H:%M:%S'
  TIME='%H:%M:%S'

  def str_to_datetime(time, format=DATE_TIME)
    unless time.blank?
      Time.strptime(time, format)
    else
      nil
    end
  end

  def datetime_to_str(time, format=DATE_TIME)
    unless time.blank?
      time.strftime(format)
    else
      nil
    end
  end

  def str_to_date(time, format=DATE)
    unless time.blank?
      Time.strptime(time, format)
    else
      nil
    end
  end

  def date_to_str(time, format=DATE)
    unless time.blank?
      time.strftime(format)
    else
      nil
    end
  end

end

app/views/alunos/_form.html.erb
<%= form_for @aluno, html: {class: "col s12 profile"} do |f| %>
  <div class="row">
    <div class="input-field col s6">
      <%= f.text_field :first_name, class: "validate", length: "25" %>
      <%= f.label :first_name, "Nome" %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :last_name, class: "validate", length: "50" %>
      <%= f.label :last_name, "Sobrenome" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :email, class: "validate", length: "75" %>
      <%= f.label :email, "Email" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
      <%= f.telephone_field :mobile, class: "validate", length: "15" %>
      <%= f.label :mobile, "Celular" %>
    </div>
    <div class="input-field col s6">
      <%= f.date_field :birthdate, class: "datepicker", value: date_to_str(@aluno.birthdate) %>
      <%= f.label :birthdate, "Nascimento" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6" style="margin-top: 0;">
      <label for="gender">Sexo</label>
      <%= f.select(:gender) do %>
        <% [['Feminino', 'F'], ['Masculino', 'M'], ['Outro', 'O']].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="input-field col s12">
      <input id="description" type="text" class="validate" length="50" value="Condomínio New Place">
      <label for="description">Local de treino<small>- ex: Condomínio La Ville</small></label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s9">
      <input id="street" type="text" class="validate" length="150" value="Av. Faria Lima">
      <label for="street">Logradouro<small>- Rua, avenida, etc.</small></label>
    </div>
    <div class="input-field col s3">
      <input id="number" type="text" class="validate" length="50" value="2928">
      <label for="number">Número</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
      <input id="complement" type="text" class="validate" length="50" value="8. andar">
      <label for="complement">Complemento</label>
    </div>
    <div class="input-field col s6">
      <input id="district" type="text" class="validate" length="75" value="Itaim Bibi">
      <label for="district">Bairro</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
      <input id="complement" type="text" class="validate" length="50" value="São Paulo">
      <label for="complement">Cidade</label>
    </div>
    <div class="input-field col s6">
      <input id="district" type="text" class="validate" length="75" value="SP">
      <label for="district">Estado/UF</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <textarea id="textarea1" class="materialize-textarea" length="255"></textarea>
      <label for="textarea1">Observações</label>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col s12">
      <a class="waves-effect waves-light btn block">Salvar</a>
    </div>
  </div>
<% end %>


<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunos/index.html.erb
<style type="text/css">
  .tabs {
    margin-top: 15px;
    margin-bottom: 15px;
  }
  .collection-item i.secondary-content {
    font-size: 1.5rem;
    color: #777;
  }
</style>

<!-- Navbar : begin -->
<%= render "commons/navbar", back_href: root_path, title: "Meus alunos" %>
<!-- Navbar : end -->

<!-- Sidenav : begin -->
<%= render "commons/sidenav" %>
<!-- Sidenav : end -->

<div class="row">
  <div class="col s12 no-padding">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#new">Novos<span class="badge" style="float: none; font-size: .7em; font-weight: 500; position: relative; top: -5px;">(<%= @alunos.select{|a| a.pending?}.count %>)</span></a></li>
      <li class="tab col s3"><a href="#actives">Ativos</a></li>
      <li class="tab col s3"><a href="#inactives"> Inativos</a></li>
    </ul>
  </div>

  <!-- Novos : begin -->
  <div id="new" class="col s12 no-padding">
    <div class="row">
      <form>
        <div class="input-field col s12" style="margin-top: 0; padding: 0 30px;">
          <input id="search" placeholder="Buscar" type="text" class="validate" length="25">
          <i class="mdi-action-search prefix" style="float: right; right: 1px; top: 1px; color: #26a69a;"></i>
        </div>
      </form>
      <div class="col s12 no-padding">
        <ul class="collection">
          <% @alunos.select{|a| a.pending?}.each do |aluno| %>
            <a href="<%= aluno_path aluno %>" class="collection-item avatar">
              <img src="<%= aluno.avatar %>" alt="" class="circle">
              <span class="title"><%= aluno.fullname %></span>
              <p style="color: #999; font-size: 1em;"><%= aluno.age %> anos - Iniciante</p>
              <i class="secondary-content mdi-navigation-chevron-right"></i>
            </a>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!-- Novos : end -->

  <!-- Ativos : begin -->
  <div id="actives" class="col s12 no-padding">
    <div class="row">
      <form>
        <div class="input-field col s12" style="margin-top: 0; padding: 0 30px;">
          <input id="search" placeholder="Buscar" type="text" class="validate" length="25">
          <i class="mdi-action-search prefix" style="float: right; right: 1px; top: 1px; color: #26a69a;"></i>
        </div>
      </form>
      <div class="col s12 no-padding">
        <ul class="collection">
          <% @alunos.select{|a| a.active?}.each do |aluno| %>
            <a href="<%= aluno_path aluno %>" class="collection-item avatar">
              <img src="<%= aluno.avatar %>" alt="" class="circle">
              <span class="title"><%= aluno.fullname %></span>
              <p style="color: #999; font-size: 1em;"><%= aluno.age %> anos - Iniciante</p>
              <i class="secondary-content mdi-navigation-chevron-right"></i>
            </a>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!-- Ativos : end -->

  <!-- Inativos : begin -->
  <div id="inactives" class="col s12 no-padding">
    <div class="row">
      <form>
        <div class="input-field col s12" style="margin-top: 0; padding: 0 30px;">
          <input id="search" placeholder="Buscar" type="text" class="validate" length="25">
          <i class="mdi-action-search prefix" style="float: right; right: 1px; top: 1px; color: #26a69a;"></i>
        </div>
      </form>
      <div class="col s12 no-padding">
        <ul class="collection">
          <% @alunos.select{|a| a.inactive?}.each do |aluno| %>
            <a href="<%= aluno_path aluno %>" class="collection-item avatar">
              <img src="<%= aluno.avatar %>" alt="" class="circle">
              <span class="title"><%= aluno.fullname %></span>
              <p style="color: #999; font-size: 1em;"><%= aluno.age %> anos - Iniciante</p>
              <i class="secondary-content mdi-navigation-chevron-right"></i>
            </a>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!-- Inativos : end -->

  <div class="row">
    <div class="col s12">
      <%= link_to "Adicionar aluno", new_aluno_path, class: "waves-effect waves-light btn block" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).on('page:load', function(){
    // Initialize collapse button
    $('#sidenav-toggle').sideNav({
        menuWidth: 300, // Default is 240
        edge: 'right', // Choose the horizontal origin
        closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
      }
    );
  });
</script>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form' %>

<%= link_to 'Back', alunos_path %>

app/views/commons/_navbar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper valign-wrapper">
      <ul class="left">
        <li><a href="<%= back_href %>"><i class="mdi-navigation-arrow-back"></i></a></li>
      </ul>
      <span class="center-block center-align">
        <span href="#!" class="flow-text valign"><%= title %></span>
      </span>
      <ul class="right">
        <li><a id="sidenav-toggle" href="#" data-activates="slide-out"><i class="mdi-navigation-menu"></i></a></li>
      </ul>
    </div>
  </nav>
</div>

app/views/commons/_sidenav.html.erb
<ul id="slide-out" class="side-nav collection with-header">
  <li class="collection-header"><h5>Alunos</h5></li>
  <a href="<%= alunos_path %>" class="collection-item active"><i class="mdi-social-people secondary-content"></i>Meus alunos</a>
  <li class="collection-header"><h5>Treinos</h5></li>
  <a href="schedule.html" class="collection-item"><i class="mdi-action-event secondary-content"></i>Agenda</a>
  <a href="#!" class="collection-item"><i class="mdi-editor-insert-chart secondary-content"></i>Relatórios</a>
  <a href="feedbacks.html" class="collection-item"><i class="mdi-notification-sms-failed secondary-content"></i>Feedbacks</a>
  <a href="workout_templates.html" class="collection-item"><i class="mdi-maps-local-attraction secondary-content"></i>Modelos</a>
  <a href="#!" class="collection-item"><i class="mdi-action-accessibility secondary-content"></i>Exercícios</a>
  <li class="collection-header"><h5>Minha conta</h5></li>
  <a href="#!" class="collection-item"><i class="mdi-action-account-circle secondary-content"></i>Perfil</a>
  <a href="signin.html" class="collection-item"><i class="mdi-action-input secondary-content"></i>Sair</a>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>Fitness Hero | Fitness na Medida Certa</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/personals/_form.html.erb
<%= form_for(@personal) do |f| %>
  <% if @personal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal.errors.count, "error") %> prohibited this personal from being saved:</h2>

      <ul>
      <% @personal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :cref %><br>
    <%= f.text_field :cref %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personals/edit.html.erb
<h1>Editing Personal</h1>

<%= render 'form' %>

<%= link_to 'Show', @personal %> |
<%= link_to 'Back', personals_path %>

app/views/personals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personals</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthdate</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Cref</th>
      <th>Gender</th>
      <th>Avatar</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personals.each do |personal| %>
      <tr>
        <td><%= personal.first_name %></td>
        <td><%= personal.last_name %></td>
        <td><%= personal.birthdate %></td>
        <td><%= personal.email %></td>
        <td><%= personal.mobile %></td>
        <td><%= personal.cref %></td>
        <td><%= personal.gender %></td>
        <td><%= personal.avatar %></td>
        <td><%= personal.status %></td>
        <td><%= personal.user_id %></td>
        <td><%= link_to 'Show', personal %></td>
        <td><%= link_to 'Edit', edit_personal_path(personal) %></td>
        <td><%= link_to 'Destroy', personal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal', new_personal_path %>

app/views/personals/new.html.erb
<h1>New Personal</h1>

<%= render 'form' %>

<%= link_to 'Back', personals_path %>

app/views/personals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @personal.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @personal.last_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @personal.birthdate %>
</p>

<p>
  <strong>Email:</strong>
  <%= @personal.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @personal.mobile %>
</p>

<p>
  <strong>Cref:</strong>
  <%= @personal.cref %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @personal.gender %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @personal.avatar %>
</p>

<p>
  <strong>Status:</strong>
  <%= @personal.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @personal.user_id %>
</p>

<%= link_to 'Edit', edit_personal_path(@personal) %> |
<%= link_to 'Back', personals_path %>